### ISSUE TITLE
Inconsistencies in layers of features aggregation

### ISSUE THREAD

**Issue by krantiparida** [intel-isl/DPT#12]
Hi, Thanks for sharing the code.
As per the paper, the features for ViT-large is taken from layers {5,12,18,24} whereas in the code it is actually taken from {6,12,18,24} (line 45, dpt/models.py). Kindly clarify the correct setting. Thanks.

**Comment by ranftlr** [comment]
Thanks for bringing this to our attention. The paper has a typo here, the code has the correct setting.
