### ISSUE TITLE
Where does the Readout Token come from?

### ISSUE THREAD

**Issue by BrianPugh** [intel-isl/DPT#16]
I don't quite follow how the Readout Token is generated (either from reading the paper or from the code). All the other tokens make sense (one per patch), but I don't get where Readout comes from.

**Comment by ranftlr** [comment]
This token is a fixed, learned token at the input. See here for its definition: https://github.com/rwightman/pytorch-image-models/blob/9cc7dda6e5fcbbc7ac5ba5d2d44050d2a8e3e38d/timm/models/vision_transformer.py#L272). Note that it is declared as a nn.Parameter, which means that it is updated during training like any other parameter. At test time this now constant input token is added to the pool of tokens, see here and the following lines: https://github.com/rwightman/pytorch-image-models/blob/9cc7dda6e5fcbbc7ac5ba5d2d44050d2a8e3e38d/timm/models/vision_transformer.py#L337

This token is something that ViT carried over from the original BERT work (it is called the [CLS] token in these works). As this token passes through the Transformer layers, you can think of it as a designated location/memory for aggregating information from all other tokens in a central place.

**Comment by BrianPugh** [comment]
Thank you so much for your response, this makes it very clear!
