### ISSUE TITLE
Model weights for DPT-Base

### ISSUE THREAD

**Issue by krantiparida** [intel-isl/DPT#18]
Hi, in the paper, you have mentioned the third variant of the DPT model, i.e. DPT-Base. Could you also share the weights for the Base model as well? Thanks.

**Comment by ranftlr** [comment]
We didn't train DPT-Base on the full dataset, only on the much smaller ablation dataset for the backbone comparison.

**Comment by krantiparida** [comment]
Ok. Thanks for the clarification.
