### ISSUE TITLE
DPT vs Monodepth2 

### ISSUE THREAD

**Issue by Ritesh1991** [intel-isl/DPT#2]
HI, I go through your paper it open new way to use transformer in depth estimation. have you compare DPT result with state of art Monocular depth estimation network Monodepth2?

**Comment by ranftlr** [comment]
The numbers in Table 1 can be directly compared to Table 11 in https://arxiv.org/abs/1907.01341 (Monodepth2 is the line "Godard [24]").

The numbers in Tables 2 and 3 can be directly compared to the corresponding numbers in the Monodepth2 paper (https://arxiv.org/pdf/1806.01260.pdf).
