### ISSUE TITLE
Question on the results on Pascal Context in Table. 5

### ISSUE THREAD

**Issue by LayneH** [intel-isl/DPT#24]
Hi,

Thank you for your great work and for sharing the code.

I have a slight question on results on Pascal Context in Table. 5: It seems that the DPT-Hybrid model is firstly pre-trained on the ADE20K dataset then finetuned on Pascal Context, am I right?

Thanks.

**Comment by ranftlr** [comment]
Correct.

**Comment by LayneH** [comment]
Got it, thanks.

**Comment by LayneH** [comment]
Hi, @ranftlr 

I wonder whether you had run experiments on Pascal Context without using ADE pre-training?
If you did, at your convenience, could you share the results? Thanks.

**Comment by ranftlr** [comment]
No, we didn't try training from scratch on Pascal Context.

**Comment by LayneH** [comment]
OK, thanks.
