### ISSUE TITLE
Output kitti finetuned and kitti evaluation

### ISSUE THREAD

**Issue by RuslanOm** [intel-isl/DPT#25]
Hi, @ranftlr !

In #10 you said, that output of kitti model is absolute depth, but, I thinks it is not. I want to calculate errors of model on kitti dataset in absolute depth values. Can you explain, please, how i can do this? 
<img width="717" alt="Снимок экрана 2021-05-24 в 16 56 18" src="https://user-images.githubusercontent.com/38555638/119358613-74d0b400-bcb1-11eb-8a34-14cf051690c8.png">

On screenshot there are predicts of hybrid kitti model

**Comment by angrysword** [comment]
why do you think it is not absolute value? The below is the code. you can see the actual result is relative value. However, after use scale and shift parameter. It become absolute value. I just dont know how did @ranftlr  get the scale and shift data?

Kitti   scale=0.00006016, shift=0.00579
NYU:   scale=0.000305,shift=0.1378

```
prediction = model.forward(sample)
prediction *= 1000.0
def forward(self, x):
    inv_depth = super().forward(x).squeeze(dim=1)
    if self.invert:
        depth = self.scale * inv_depth + self.shift
        depth[depth < 1e-8] = 1e-8
        depth = 1.0 / depth
        return depth
    else:
        return inv_depth
```

**Comment by RuslanOm** [comment]
Ok, I see. But I still have a question: in what units is it? Meters or something else? 

This result made from kitti image and bottom values should by around 6 meters.

**Comment by ranftlr** [comment]
Units are compatible to the KITTI ground truth. Please see here: https://github.com/intel-isl/DPT/blob/main/EVALUATION.md
