### ISSUE TITLE
hows the inference speed compares to monodepth2 in terms of same accuracy?

### ISSUE THREAD

**Issue by jinfagang** [intel-isl/DPT#29]
hows the inference speed compares to monodepth2 in terms of same accuracy?

**Comment by ranftlr** [comment]
Not sure how to answer this question as there is no "same accuracy". These are different models that have been trained in a different way and as such will always have different accuracy on any given dataset. 

As both are freely available, I suggest to just run both yourself and see what works better for your use case.

**Comment by jinfagang** [comment]
@ranftlr  I am closely performance, say mAP both 35-36, and compare the speed. I am not sure if DPT can run efficient.

**Comment by ranftlr** [comment]
Ok, feel free to (or also not to) try and judge yourself. Setup of DPT takes about a minute.

**Comment by jinfagang** [comment]
@ranftlr Do u think DPT is faster and accurater?

**Comment by phamdat09** [comment]
@jinfagang As I tested, DPT is much accurate than monodepth2. But the speed is slower.
Just see the size of 2 models, I can guess the speed of both

**Comment by pengzhi1998** [comment]
@phamdat09 Sorry to bother you. But how long will it take for DPT-large to estimate an image's depth value?

**Comment by phamdat09** [comment]
> @phamdat09 Sorry to bother you. But how long will it take for DPT-large to estimate an image's depth value?

as I tested with Tensorrt avec Rtx2080. FPS is around 20 including pre-processing and post-processing

**Comment by pengzhi1998** [comment]
@phamdat09 Thank you!

**Comment by pengzhi1998** [comment]
@phamdat09 Sorry to bother you again. But when using RTX1060 to test DPT-large or DPT-hybrid, the networks both can only predict only one depth estimation within a second. Do you have any idea what might cause the problem of low efficiency?

**Comment by pengzhi1998** [comment]
@phamdat09 Sorry to bother you again. But have you seen [this](https://github.com/isl-org/DPT/issues/59) issue before?
