### ISSUE TITLE
Links to models fine-tuned on KITTI and NYU are broken

### ISSUE THREAD

**Issue by MRLoghmani** [intel-isl/DPT#30]

**Comment by ranftlr** [comment]
Weird, the links work for me. Seems like a issue with GitHub. 

Here are alternative download links:

NYU: https://drive.google.com/file/d/1NjiFw1Z9lUAfTPZu4uQ9gourVwvmd58O/view?usp=sharing
KITTI: https://drive.google.com/file/d/1-oJpORoJEdxj4LTV-Pc17iB-smp-khcX/view?usp=sharing
