### ISSUE TITLE
have you ever tried any smaller size model?

### ISSUE THREAD

**Issue by mwsunshine** [intel-isl/DPT#39]
Dear author,

Many thanks for your impressive work which enlightens me a lot!

Great as the result is, the model ussally uses vit-base or vit-large or vit-hybrid and the size is large.

I am wondering whether have you tried to train a model with smaller size? Like vit-small or vit-tiny? I want to train a smaller size model myself, but the result is quite disappointing.

**Comment by ranftlr** [comment]
We haven't used vit-small or vit-tiny, so I can't really comment on their performance in this context. At least for depth estimation, large capacity helps with training, so some loss in performance is obviously expected when going to smaller backbones.

For depth estimation we provide a small model (although based on EfficientNet) here: https://github.com/intel-isl/MiDaS
