### ISSUE TITLE
CUBLAS_STATUS_EXECUTION_FAILED when calling cublasGemmEx

### ISSUE THREAD

**Issue by LeRoii** [intel-isl/DPT#4]
hi,
I got this error when I ran ```run_segmentation.py```, my environment is the same as mentioned in README.md and CUDA version is 10.2, this might be the problem, what the CUDA version did you use?
```
x = F.conv2d(x, self.get_weight(), self.bias, self.stride, self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`
```

**Comment by ranftlr** [comment]
Yes, likely a CUDA issue. We tested with CUDA 11.2. You can also switch to CPU mode by changing this line 

https://github.com/intel-isl/DPT/blob/822b5f740dc46193e8975023291dcbf4ea24ec83/run_monodepth.py#L31

and/or the corresponding line in run_segmentation.py to `device = torch.device("cpu")`

**Comment by laisimiao** [comment]
@LeRoii Have you solved this CUDA error under GPU? I also have this issue on cuda10.2
