### ISSUE TITLE
Typo in the paper

### ISSUE THREAD

**Issue by jinsuyoo** [intel-isl/DPT#40]
Dear authors,

While reading your great work, I recognized that there are typical typo in page 4 (l = {5, 12, 18, 24}). Maybe 5 needs to be 6 comparing with the provided code ?

Anyway, thank you for bringing transformer to the image regression community !

**Comment by ranftlr** [comment]
Thanks for bringing this to our attention. Yes, the code is correct, it should be 6 instead of 5. We will fix this typo in the next revisions.
