### ISSUE TITLE
timm update, slight breakage for dist_token

### ISSUE THREAD

**Issue by rwightman** [intel-isl/DPT#5]
@ranftlr @dvdhfnr I updated the vit models on timm master, no pypi update yet but there will be a small breakage when I do. I tried to keep everything compat with downstream uses like this but ran into one issue.

At https://github.com/intel-isl/DPT/blob/main/dpt/vit.py#L181-L191

`if hasattr(self, "dist_token"):`

should be changed to

`if getattr(self, "dist_token", None) is not None:`

I merged the distilled and normal model class so that torchscript works for both (torchscript doesn't work well with inheritence). torchscript also likes None values as sentinels for non-used modules, so I couldn't leave it out entirely when not in use.

**Comment by rwightman** [comment]
Note the fix works for all timm vit versions, not just the new code.

**Comment by ranftlr** [comment]
Fixed. Thanks for the heads-up!
