### ISSUE TITLE
RGB Depth estimation

### ISSUE THREAD

**Issue by ChiscoD** [intel-isl/DPT#7]
In the paper, depths are showed as red when is near, and black when in far, how can I replicate the papers result? (color).

**Comment by ranftlr** [comment]
The visualization uses the "inferno" colormap from matplotlib:

```python
import matplotlib.pyplot as plt
plt.imshow(pred, cmap=plt.cm.inferno)
```

**Comment by ChiscoD** [comment]
Thanks
