### ISSUE TITLE
Values in Tables 2 and 3 in paper

### ISSUE THREAD

**Issue by tarashakhurana** [intel-isl/DPT#8]
I'm a bit confused by the absolute numbers in Tables 2 and 3 in the arxiv release. <img src="https://render.githubusercontent.com/render/math?math=\delta > 1.25"> should be a percentage of pixels out of 100 and lower should be better. However, the range of numbers in the tables is very low and the higher numbers are highlighted. Could you please clarify what the numbers represent?

**Comment by ranftlr** [comment]
Thanks for bringing this to our attention. This is an error in the column headings. The numbers in Tables 2 and 3 are actually \delta < 1.25, i.e. it is the percentage of *correct* values (higher is better - as it is most commonly reported in the literature). The corresponding column in Table 1 is marked correctly, it shows the percentage of *incorrect* values (lower is better).

Sorry for the confusion, we will fix it in the next revision.

**Comment by tarashakhurana** [comment]
Thanks for your reply! Does that mean DPT-Hybrid does not improve with finetuning on NYUv2? The number for it in Table 1 is 8.69% and the corresponding number from Table 2 should be 100-90.4=9.6%. Or should I not be comparing these two numbers?

**Comment by ranftlr** [comment]
The numbers between the tables are not comparable. Table 1 evaluates affine-invariant depth. To compute the metrics we first align the predictions to the ground-truth in terms of a global scale and shift before measuring errors. Tables 2 and 3 evaluate absolute depth, so no pre-alignment is happening.

**Comment by tarashakhurana** [comment]
Got it! Thanks a lot for the clarification!

**Comment by tarashakhurana** [comment]
I have a follow-up. For the finetuning on NYUv2, did you use the training set of 795 images from the labeled dataset or was the raw data used (120k training images)?

**Comment by ranftlr** [comment]
We use a subset of about 24k pairs from the raw data, as proposed in [BTS](https://arxiv.org/pdf/1907.10326.pdf). Please have a look at their paper and repo for details.
