### ISSUE TITLE
run Problem

### ISSUE THREAD

**Issue by MyHubTo** [intel-isl/DPT#9]
Dear Author:
thank u for the excellent works.
when i run the code `run_segmentation.py`test on CPU there are some problem :
/home/mrzhao/anaconda3/envs/DPT/lib/python3.7/site-packages/torch/nn/functional.py:3455: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)
Segmentation fault (core dumped)

and I change the code  align_corners=False to  align_corners=True.
but it not working.
(test with cuda is good)  
so ,what should i do to solve this problem;

**Comment by ranftlr** [comment]
The warning about "align_corners" has nothing to do with this error. This is very likely an issues with your PyTorch setup. Recommend installing in a fresh environment.

**Comment by duymanhdoan** [comment]
I solved problem.
the problem is opencv version base on c++, so that is Segmentation fault
just typed the commandline to change version of opencv:
$ pip3 install opencv-python==4.0.1.24
